name: ToDo
description: Simple ToDo application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  shared_preferences: 0.5.12+4
  localstorage: 3.0.3+6
  rxdart: 0.24.1
  dynamic_theme: 1.0.1
  provider: 4.3.2+2

  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  mockito: 4.1.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
